name: dependency_injection
description: Provides dependency injection for the app
publish_to: 'none'

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true