name: wahl_analytics

environment:
  sdk: '>=2.18.0 <3.0.0'

packages:
  # Include the package in the workspace root.
  - .
  # Include all packages inside the `layers` directory that are direct children.
  - layer/*
  # Include all packages inside the `layers` directory that are direct children.
  - tool/*

scripts:
  # Flutter packages scripts
  version:
    run: flutter --version
    description: Run `flutter version` in all packages.
    exec:
      concurrency: 1
    packageFilters:
      flutter: true

  get:
    run: flutter pub get
    description: Run `flutter pub get` in all packages.
    exec:
      concurrency: 1
    packageFilters:
      flutter: true

  gen:
    run: dart run build_runner build --delete-conflicting-outputs
    description: Run `build_runner` in all packages.
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: build_runner

  format:
    run: dart format lib test --set-exit-if-changed
    description: Run `flutter format` in all packages.
    exec:
      concurrency: 1

  analyze:
    run: flutter analyze
    description: Run `flutter analyze` in all packages.
    exec:
      concurrency: 1
    packageFilters:
      flutter: true

  analyze_fix:
    run: |
      dart fix --dry-run
      dart fix --apply
      dart format .
      flutter analyze
      flutter pub get
    description: Run `flutter analyze` and fix issues in all packages.
    exec:
      concurrency: 1
    packageFilters:
      flutter: true

  # Cleaning commands
  clean:
    run: flutter clean
    description: Run `flutter clean` in all packages.
    exec:
      concurrency: 1
    packageFilters:
      flutter: true

  cache_clean:
    run: |
      flutter clean
      flutter pub cache repair
      flutter pub get
    description: Clean cache.
    exec:
      concurrency: 1

  ios_clean:
    run: |
      rm -rf ios/Pods/*
      rm -f ios/Podfile.lock
      rm -r ios/.symlinks
      rm -r ios/Flutter/Flutter.framework
      rm -f ios/Flutter/Flutter.podspec
      flutter clean
      flutter pub get
      cd ios 
      pod cache clean --all
      pod repo update
      cd ..
      flutter pub get
      cd ios
      pod install
    description: Clean cache.

  # Test commands
  test:
    run: flutter test --exclude-tags 'golden'
    description: Run `flutter test` in all packages.
    exec:
      concurrency: 1
    packageFilters:
      flutter: true

  update_golden_test:
    run: flutter test --tags golden --update-goldens
    description: Update `golden` test files in all packages.
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: alchemist

  golden_test:
    run: flutter test --tags golden
    description: Run `golden` tests in all packages.
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: alchemist

  golden_test_in_ci:
    run: flutter test --tags golden --dart-define=CI=true
    description: Run `golden` tests in all packages.
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: alchemist

  # Splash command
  gen_splash:
    run: |
      flutter clean
      flutter pub get
      dart run flutter_native_splash:create --path=native_splash.yaml
    description: Generate splash screen for all flavors.
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: flutter_native_splash


  # Run commands
  run_prod:
    run: flutter run lib/main.dart  --dart-define=build_env=prod
    description: Run the app in prod env.

  run_prod_web_release:
    run: flutter run lib/main.dart  --dart-define=build_env=prod --release -d chrome --web-port=1234
    description: Run the app in prod env.

  run_prod_web:
    run: flutter run lib/main.dart  --dart-define=build_env=staging -d chrome --web-port=1234
    description: Run the app in prod env.

  run_staging:
    run: flutter run lib/main.dart  --dart-define=build_env=staging
    description: Run the app in prod env.


  # Helper commands
  module_checks:
    run: |
      flutter analyze
      dart fix --dry-run
      dart fix --apply
      dart format .
      flutter analyze
      flutter pub get
      flutter test --exclude-tags 'golden'
    description: Run analyze, fix, format, test a module
    exec:
      concurrency: 1
    packageFilters:
      flutter: true

  # CI Helper commands
  test_with_coverage:
    run: flutter test --exclude-tags golden --coverage --machine > test-results.json --no-pub
    description: Run all the test with coverage
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: test

  gen_app:
    run: dart run build_runner build --delete-conflicting-outputs
    description: Run `build_runner` in all packages.
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: build_runner
      ignore:
        - storybook


  # Firebase hosting
  host_web:
    run: |
      echo "Clean existing repository"
      flutter clean
      echo "Getting packages"
      flutter pub get 
      echo "Building web with Flutter"
      flutter build web --release --dart-define=build_env=prod --no-tree-shake-icons
      echo "Deploying to Firebase"
      firebase deploy --only hosting
    description: Host flutter web page

  host_storybook:
    run: |
      cd tool/storybook
      echo "Clean existing repository"
      flutter clean
      echo "Getting packages"
      flutter pub get 
      echo "Building web with Flutter"
      flutter build web --release
      echo "Deploying to Firebase"
      firebase deploy --only hosting:wahl-consultancy-storybook-320bf-5669e --project wahl-consultancy-storybook-320bf-5669e
    description: Host flutter web page

  # Firebase function deploy
  host_functions:
    run: |
      cd tool/firebase_function/functions
      firebase deploy --only functions
    description: Deploy firebase functions

  # Firestore Content Uploader commands
  upload_firestore_staging_content:
    run: |
      cd tool/firestore_content_uploader
      dart pub get
      dart run bin/firestore_content_uploader.dart upload --env staging --document business_client --credentials ../data/credentials/service_account.json --data ../data/firestore/staging/section_business_client.json
      dart run bin/firestore_content_uploader.dart upload --env staging --document business_contact --credentials ../data/credentials/service_account.json --data ../data/firestore/staging/section_business_contact.json
      dart run bin/firestore_content_uploader.dart upload --env staging --document business_info --credentials ../data/credentials/service_account.json --data ../data/firestore/staging/section_business_info.json
      dart run bin/firestore_content_uploader.dart upload --env staging --document business_service --credentials ../data/credentials/service_account.json --data ../data/firestore/staging/section_business_service.json
      dart run bin/firestore_content_uploader.dart upload --env staging --document business_team --credentials ../data/credentials/service_account.json --data ../data/firestore/staging/section_business_team.json
    description: Upload the content to Firestore for staging env
    packageFilters:
      dirExists: tool/firestore_content_uploader

  upload_firestore_prod_content:
    run: |
      cd tool/firestore_content_uploader
      dart pub get
      dart run bin/firestore_content_uploader.dart upload --env prod --document business_client --credentials ../data/credentials/service_account.json --data ../data/firestore/prod/section_business_client.json
      dart run bin/firestore_content_uploader.dart upload --env prod --document business_contact --credentials ../data/credentials/service_account.json --data ../data/firestore/prod/section_business_contact.json
      dart run bin/firestore_content_uploader.dart upload --env prod --document business_info --credentials ../data/credentials/service_account.json --data ../data/firestore/prod/section_business_info.json
      dart run bin/firestore_content_uploader.dart upload --env prod --document business_service --credentials ../data/credentials/service_account.json --data ../data/firestore/prod/section_business_service.json
      dart run bin/firestore_content_uploader.dart upload --env prod --document business_team --credentials ../data/credentials/service_account.json --data ../data/firestore/prod/section_business_team.json
    description: Upload the content to Firestore for staging env
    packageFilters:
      dirExists: tool/firestore_content_uploader