name: wahl_analytics
description: "Dashboard app for Wahl Analytics"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

workspace:
  - layer/cache
  - layer/core
  - layer/dependency_injection
  - layer/design_system
  - layer/error_reporter
  - layer/feature_flag
  - layer/firebase
  - layer/log_reporter
  - layer/remote
  - layer/use_case

dependencies:
  cache:
    path: layer/cache
  collection: ^1.19.0
  core:
    path: layer/core
  cupertino_icons: ^1.0.8
  dependency_injection:
    path: layer/dependency_injection
  design_system:
    path: layer/design_system
  equatable: ^2.0.7
  error_reporter:
    path: layer/error_reporter
  feature_flag:
    path: layer/feature_flag
  file_picker: ^8.1.7
  firebase:
    path: layer/firebase
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  go_router: ^14.6.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  log_reporter:
    path: layer/log_reporter
  meta: ^1.15.0
  open_file: ^3.5.10
  package_info_plus: ^8.1.2
  recase: ^4.1.0
  remote:
    path: layer/remote
  url_launcher: ^6.3.1
  use_case:
    path: layer/use_case

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.2
  lint: ^2.3.0
  melos: ^6.3.0
  mocktail: ^1.0.4
  test: ^1.24.9

flutter:
  uses-material-design: true