name: firestore_content_uploader
description: A command-line application for uploading content to Firestore.
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  args: ^2.7.0
  get_it: ^8.2.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  http: ^1.5.0
  logger: ^2.6.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.24.9
