/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
library;

import 'package:flutter/widgets.dart';

class DSIcons {
  DSIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String _kFontPkg = 'design_system';

  static List<IconData> get all {
    return [
      DSIcons.chart_line,
      DSIcons.multiline_chart,
      DSIcons.storage,
      DSIcons.swap_vert,
      DSIcons.wb_cloudy,
      DSIcons.chart_bar,
      DSIcons.database,
      DSIcons.lifebuoy,
      DSIcons.chart_area,
    ];
  }

  static const IconData chart_line = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData multiline_chart = IconData(
    0xea23,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData storage = IconData(
    0xeb1d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData swap_vert = IconData(
    0xeb2e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData wb_cloudy = IconData(
    0xeb91,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData chart_bar = IconData(
    0xec3d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData database = IconData(
    0xf1c0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData lifebuoy = IconData(
    0xf1cd,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData chart_area = IconData(
    0xf1fe,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
