name: storybook
description: "Storybook web project for design system in Wahl Analytics"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.8
  design_system:
    path: ../../layer/design_system
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  widgetbook: ^3.10.1
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.9.1

flutter:
  uses-material-design: true