name: Deploy Storybook to firebase

on:
  workflow_call:
    inputs:
      channelId:
        type: string
        required: true
    secrets:
      FIREBASE_SERVICE_ACCOUNT:
        required: true
      FIREBASE_PROJECT_ID:
        required: true
      FIREBASE_JSON_BASE64:
        required: true

env:
  FLUTTER_VERSION: 3.32.2
  STORYBOOK_PATH: ./tool/storybook

jobs:
 deploy:
    name: Deploy to firebase
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.STORYBOOK_PATH }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: stable
          cache: true

      - name: Set version from tag
        run: |
          if [ "$GITHUB_REF_TYPE" != "tag" ]
          then
            echo "Ref name $GITHUB_REF_NAME is not a tag but a $GITHUB_REF_TYPE, not setting version number"
          else
            version=$(echo $GITHUB_REF_NAME | sed "s/-storybook-prod//") && sed -i "s/^version: .*$/version: $version/g" pubspec.yaml
          fi

      - name: Decode Firebase Json
        run: |
          echo "${{ secrets.FIREBASE_JSON_BASE64 }}" | base64 --decode > firebase.json

      - name: Get dart dependencies
        run: flutter pub get

      - name: Run code generators
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Flutter Web
        run: flutter build web --release

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          entryPoint: ${{ env.STORYBOOK_PATH }}
          channelId: ${{ inputs.channelId }}