name: Analyze and test Storybook app

on:
  workflow_call:

env:
  FLUTTER_VERSION: 3.32.2
  STORYBOOK_PATH: ./tool/storybook

jobs:
  analyze-and-test:
    name: Format, analyze, and test Storybook
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.STORYBOOK_PATH }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: stable
          cache: true

      - name: Get dart dependencies
        run: flutter pub get

      - name: Format the Dart code
        run: dart format . --set-exit-if-changed

      - name: Run code generators
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Statically analyze the Dart code
        run: flutter analyze

      - name: Run unit tests
        run: flutter test --exclude-tags golden --coverage --machine > test-results.json  --no-pub

      - name: Generate test report
        uses: dorny/test-reporter@v1.9.1
        if: always()
        with:
          name: Test Results
          path: test-results.json
          reporter: flutter-json
          working-directory: ${{ env.STORYBOOK_PATH }}
          token: ${{ secrets.GITHUB_TOKEN }}