name: Deploy Storybook to firebase

on:
  workflow_call:
    inputs:
      path:
        type: string
        required: true
      channelId:
        type: string
        required: true

env:
  FLUTTER_VERSION: 3.27.1

jobs:
 deploy:
    name: Deploy to firebase
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup the flutter environment
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: stable
          cache: true

      - name: Get dart dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.STORYBOOK_FIREBASE_SERVICE_ACCOUNT }}"
          projectId: ${{ secrets.STORYBOOK_FIREBASE_PROJECT_ID }}
          entryPoint:  ${{ inputs.path }}
          channelId: ${{ inputs.channelId }}