name: Cache layer code quality validation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
    #paths:
    #  - 'layer/cache/**'
    #  - '.github/workflows/layer_cache_code_quality_validation.yaml'

permissions:
  checks: write

jobs:
  layer_cache_code_quality_validation:
    uses: ./.github/workflows/_layer_static_analyze_with_test.yaml
    with:
      module_path: 'cache'
      has_build_runner: 'false'

