name: Design System layer code quality validation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
    #paths:
    #  - 'layers/core/**'
    #  - '.github/workflows/layer_core.yaml'

permissions:
  checks: write

jobs:
  validate_code_quality:
    uses: ./.github/workflows/_validate_layer.yaml
    with:
      module_path: './layer/design_system'
      should_run_golden_test: 'true'
      has_build_runner: 'true'