name: Firebase layer code quality validation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
    paths:
      - 'layer/firebase/**'
      - '.github/workflows/layer_firebase_code_quality_validation.yaml'

env:
  DART_SDK_VERSION: 3.6.0
  FLUTTER_VERSION: 3.27.1

permissions:
  checks: write


jobs:
  layer_firebase_code_quality_validation:
    uses: ./.github/workflows/_layer_static_analyze_with_test.yaml
    with:
      module_path: './layer/firebase'
      has_build_runner: 'false'
