name: Use Case layer code quality validation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
    paths:
      - 'layer/use_case/**'
      - '.github/workflows/layer_use_case_quality_validation.yaml'

permissions:
  checks: write

jobs:
  layer_use_case_quality_validation:
    uses: ./.github/workflows/_layer_static_analyze_with_test.yaml
    with:
      module_path: './layer/use_case'
      has_build_runner: 'false'

