name: Firebase layer code quality validation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
    #paths:
    #  - 'layers/core/**'
    #  - '.github/workflows/layer_core.yaml'

permissions:
  checks: write

jobs:
  setup_firebase_options:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Decode Firebase Options
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS_BASE64 }}" | base64 --decode > lib/src/firebase_options.dart
        env:
          FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}

  validate_code_quality:
    uses: ./.github/workflows/_validate_layer.yaml
    with:
      module_path: './layer/firebase'
      should_run_golden_test: 'false'
      has_build_runner: 'false'

