name: Cache layer code quality validation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
    #paths:
    #  - 'layers/cache/**'
    #  - '.github/workflows/layer_cache.yaml'

permissions:
  checks: write

jobs:
  validate_code_quality:
    uses: ./.github/workflows/_layer_static_analyze_with_test.yaml
    with:
      module_path: './layer/cache'
      has_build_runner: 'false'

