name: Remote layer code quality validation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
    paths:
      - 'layer/remote/**'
      - '.github/workflows/layer_remote_quality_validation.yaml'
      - '.github/workflows/_layer_static_analyze_with_test.yaml'

permissions:
  checks: write

jobs:
  layer_remote_quality_validation:
    uses: ./.github/workflows/_layer_static_analyze_with_test.yaml
    with:
      module_path: './layer/remote'
      has_build_runner: 'false'

