name: Storybook web preview release and hosting

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'tool/storybook/**'
      - 'layer/design_system/**'

permissions: write-all

jobs:
  storybook_code_quality_validation:
    uses: ./.github/workflows/_storybook_static_analyze_with_test.yaml

  storybook_web_hosting:
    uses: ./.github/workflows/_build_and_distribute_storybook_web.yaml
    needs: [storybook_code_quality_validation]
    with:
      channelId: 'preview'
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_JSON_BASE64: ${{ secrets.STORYBOOK_FIREBASE_JSON_BASE64 }}