name: Storybook web release and hosting

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - '*-prod-storybook'

permissions: write-all

jobs:
  storybook_build_release_notes:
    uses: ./.github/workflows/_build_release_notes.yaml
    with:
      preRelease: false

  storybook_code_quality_validation:
    uses: ./.github/workflows/_storybook_static_analyze_with_test.yaml

  storybook_web_hosting:
    uses: ./.github/workflows/_build_and_distribute_storybook_web.yaml
    needs: [storybook_code_quality_validation]
    with:
      channelId: 'live'
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_JSON_BASE64: ${{ secrets.STORYBOOK_FIREBASE_JSON_BASE64 }}
