name: Storybook web preview release and hosting

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - 'tool/storybook/**'
      - 'layer/design_system/**'


jobs:
  code_quality_validation:
    uses: ./.github/workflows/_storybook_static_analysis.yaml
    with:
      path: './tool/storybook'

  storybook_deploy:
    uses: ./.github/workflows/_storybook_deploy.yaml
    needs: [code_quality_validation]
    with:
      path: './tool/storybook'
      channelId: 'preview'