name: Validate code quality of Storybook

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*-review'
      - '*-prod'
      - "*-storybook-prod"
    paths:
      - 'tool/storybook/**'
      - '.github/workflows/storybook_code_quality_validation.yaml'

jobs:
  storybook_code_quality_validation:
    uses: ./.github/workflows/_storybook_static_analysis.yaml