name: Storybook web release and hosting

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "*-storybook-prod"

jobs:
  build_release_notes:
    uses: ./.github/workflows/_storybook_build_release_notes.yaml
    with:
      preRelease: false

  code_quality_validation:
    uses: ./.github/workflows/_storybook_static_analysis.yaml
    needs: [build_release_notes]

  storybook_deploy:
    uses: ./.github/workflows/_storybook_deploy.yaml
    needs: [code_quality_validation]
    with:
      channelId: 'live'
    secrets:
      STORYBOOK_FIREBASE_SERVICE_ACCOUNT: ${{ secrets.STORYBOOK_FIREBASE_SERVICE_ACCOUNT }}
      STORYBOOK_FIREBASE_PROJECT_ID: ${{ secrets.STORYBOOK_FIREBASE_PROJECT_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
