name: Preview web release and hosting

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "*-review"
    tags-ignore:
      - "*-prod"
      - "*-storybook-prod"

permissions: write-all

jobs:
  wahl_analytics_code_quality_validation:
    uses: ./.github/workflows/_app_static_analyze_with_test.yaml
    secrets:
      FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}
      APP_CHECK_TOKEN_BASE64: ${{ secrets.APP_CHECK_TOKEN_BASE64 }}

  wahl_analytics_preview_hosting:
    uses: ./.github/workflows/_wahl_analytics_web_hosting.yaml
    needs: [wahl_analytics_code_quality_validation]
    with:
      channelId: 'preview'
    secrets:
      FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}
      APP_CHECK_TOKEN_BASE64: ${{ secrets.APP_CHECK_TOKEN_BASE64 }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.STORYBOOK_FIREBASE_SERVICE_ACCOUNT }}
      FIREBASE_PROJECT_ID: ${{ secrets.STORYBOOK_FIREBASE_PROJECT_ID }}
      FIREBASE_JSON_BASE64: ${{ secrets.STORYBOOK_FIREBASE_JSON_BASE64 }}
